[colors.primary]
background = "#191724"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 100
lines = 50

[window.padding]
x = 15
y = 15
