#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config external_bar                 off:45:0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  40
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   8

# Desktop 1
yabai -m space 1 --label web
yabai -m rule --add app="^Brave Browser$" space=web

# Desktop 2
yabai -m space 2 --label terminal
yabai -m rule --add app="^iTerm.*$" space=terminal

#Desktop 3
yabai -m space 3 --label code
yabai -m rule --add app="^GoLand.*$" space=code
yabai -m rule --add app="^GoLand.*$" title="Preferences" space=code manage=off

#Desktop 4
yabai -m space 4 --label slack
yabai -m rule --add app="^Slack$" space=slack

# specific space settings
# yabai -m config --space mail  layout        stack
# yabai -m config --space games layout        float

# exceptions
applications="(System Preferences|Finder)"
yabai -m rule --add app="${applications}" manage=off mouse_follows_focus=off
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off

# signals
# yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
# yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
# yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
# yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

echo "yabai configuration loaded.."
